
--DROP DATABASE PruebaExamen
create database PruebaExamen;

USE PruebaExamen;

CREATE TABLE TIPO(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50)
);


CREATE TABLE PRODUCTOS(
SKU VARCHAR(50),
FERT VARCHAR(50),
MODELO VARCHAR(50),
FECHA DATE,
NUMEROS VARCHAR(50),
TIPO INT FOREIGN KEY REFERENCES TIPO(ID)
);


INSERT INTO TIPO VALUES
('TRABAJO')
,('DEPORTIVO')
,('INFANTIL');


INSERT INTO PRODUCTOS VALUES
('123321','UNO','2019',GETDATE(),'JVH212',1),
('111111','DOS','2020',GETDATE(),'UIJ32',2),
('222222','TRES','2021',GETDATE(),'HGC32',3);


CREATE PROCEDURE TAREAS
(
@BANDERA INT = NULL,
@SKU VARCHAR(50) = NULL,
@FERT VARCHAR(50) = NULL,
@MODELO VARCHAR(50) = NULL, 
@TIPO INT = NULL,
@NUMEROS VARCHAR(50) = NULL,
@FECHA DATE = NULL,
@BUSQUEDA INT = NULL
)
AS
BEGIN 

--EDITAR
IF @BANDERA = 1
BEGIN

UPDATE PRODUCTOS
SET FERT = @FERT,
MODELO = @MODELO,
TIPO = @TIPO,
NUMEROS = @NUMEROS,
FECHA = @FECHA
WHERE SKU = @SKU;
SELECT 'REGISTRO ACTUALIZADO';

END;

--ELIMINAR
IF @BANDERA = 2
BEGIN 

DELETE FROM PRODUCTOS WHERE SKU = @SKU;
SELECT 'REGISTRO ELIMINDO'

END;

--AGREGAR
IF @BANDERA = 3
BEGIN

INSERT INTO PRODUCTOS VALUES(@SKU,@FERT,@MODELO,@FECHA,@NUMEROS,@TIPO);
SELECT 'REGISTRO GUARDADO'

END;

--BUSQUEDA
IF @BANDERA = 4
BEGIN
 --TODOS
 IF @BUSQUEDA = 1
 BEGIN
   SELECT SKU,FERT,MODELO,FECHA,(SELECT NOMBRE FROM TIPO WHERE ID=TIPO) AS TIPO FROM PRODUCTOS;
 END;
 --MODELO
 IF @BUSQUEDA = 2
 BEGIN
   SELECT SKU,FERT,MODELO,FECHA,(SELECT NOMBRE FROM TIPO WHERE ID=TIPO) AS TIPO FROM PRODUCTOS WHERE MODELO LIKE '%'+@MODELO+'%';
 END;
 --SKU
 IF @BUSQUEDA = 3
 BEGIN
   SELECT SKU,FERT,MODELO,FECHA,(SELECT NOMBRE FROM TIPO WHERE ID=TIPO) AS TIPO FROM PRODUCTOS WHERE MODELO LIKE '%'+@MODELO+'%';
 END;

END;
END;